name: Verify DNS zones
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # run on PR to test contributions
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # first load the base branch
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # and then the PR commit
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: OSAS/dns4tenants-validation@main
